### PR TITLE
Integration with the Bees mod

### PR DESCRIPTION
**Pull request by Lesya-cpp**
Added bee hive with tubes support;

Added a new techage machine -- Honey Extractor;

Added the honey extracting recipe to the crafting guides;

### CODE REVIEW

**Comment by joe7575** [comment]
Holy Moly, Great work!
Why did you do a PR and not make this as your own TA extension mod?
I can't technical reasons.
(This isn't meant to be a criticism, I just want to understand)

**Comment by Lesya-cpp** [comment]
I just want this changes to be upstream and not third party addon. Cause I think many players and public servers would not install a third party addon, but definitely install a techage update :)

**Comment by joe7575** [comment]
Ok, I understand.

But that's a nice addition, not a core feature. Techage is already so huge and contains far too many blocks.
At some point I have to set a rule as to what I still allow as PR and what no longer. I'd love to see more mods created "around" Techage.

I fear that if this is an addon that _"many players and public servers would not install"_, then at some point Techage will not be installed anymore because of too many non-core features.

**Comment by Lesya-cpp** [comment]
> I fear that if this is an addon that "many players and public servers would not install", then at some point Techage will not be installed anymore because of too many non-core features.

I mean many players and public servers would not install _any third party addon_, not just this addon.

But ok, if you insist, I could make an addon :)

**Comment by joe7575** [comment]
If you make your own mod, I will add a link to your mod in the readme.
On my server, I have bees from [mobs_animal](https://notabug.org/tenplus1/mobs_animal)
Can you support mobs_animal, too?

**Comment by Lesya-cpp** [comment]
Ok, I'll separate my code to a new mod ta_apiary.

It seems like I could add [mobs_animal](https://notabug.org/tenplus1/mobs_animal) support too :)

**Comment by Lesya-cpp** [comment]
https://gitlab.com/lesya_minetest_mods/ta_apiary

**Comment by joe7575** [comment]
See https://github.com/joe7575/techage#readme

**Pull request closed without merging**
