### PR TITLE
mark all airlike nodes at server startup

### PR DESCRIPTION
**Pull request by Niklp09**

### CODE REVIEW

**Comment by joe7575** [comment]
What is the reason for this PR?

**Comment by Niklp09** [comment]
Your current variant doesn't even cover all airlike nodes supplied by mtg, this one does and the maintenance effort will be lower in long term view.

**Comment by joe7575** [comment]
It was not intended to cover all "airlike" blocks. It is only about the blocks that are set unintentionally. For example, if a player walks to the sensor with a torch, the wielded_light mod sets light-blocks, which then trigger the sensor.
Do you have other blocks, which should be added to the black-list?

**Comment by Niklp09** [comment]
Then would be an API function very helpful.

**Pull request closed without merging**
